# Generated by Django 5.2 on 2025-06-12 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='אימייל משתמש')),
                ('restaurant_name', models.CharField(max_length=255, verbose_name='שם המסעדה')),
                ('restaurant_lat', models.FloatField(verbose_name='קואורדינטת רוחב')),
                ('restaurant_lng', models.FloatField(verbose_name='קואורדינטת אורך')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג (1-5 כוכבים)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='כותרת הביקורת')),
                ('content', models.TextField(verbose_name='תוכן הביקורת')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('is_approved', models.BooleanField(default=True, verbose_name='אושר למעקב')),
                ('tags', models.CharField(blank=True, help_text='תגיות מופרדות בפסיקים', max_length=200)),
            ],
            options={
                'verbose_name': 'ביקורת',
                'verbose_name_plural': 'ביקורות',
                'ordering': ['-created_at'],
                'unique_together': {('user_email', 'restaurant_name', 'restaurant_lat', 'restaurant_lng')},
            },
        ),
    ]
